In [3]:
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 150)

print("Environment is ready!")

Environment is ready!

In [4]:
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "raw"

print("Project Root :", PROJECT_ROOT)
print("Data Folder  :", DATA_DIR)
print("Folder Exists:", DATA_DIR.exists())

Project Root : c:\Users\asus\Documents\insurance-ai-copilot
Data Folder  : c:\Users\asus\Documents\insurance-ai-copilot\data\raw
Folder Exists: True

In [5]:
for file in DATA_DIR.iterdir():
    print(file.name)

agents.csv
claims.csv
customers.csv
policies.csv
premiums.csv
renewals.csv
underwriting.csv

In [6]:
customers = pd.read_csv(DATA_DIR / "customers.csv")
policies = pd.read_csv(DATA_DIR / "policies.csv")
claims = pd.read_csv(DATA_DIR / "claims.csv")
premiums = pd.read_csv(DATA_DIR / "premiums.csv")
renewals = pd.read_csv(DATA_DIR / "renewals.csv")
underwriting = pd.read_csv(DATA_DIR / "underwriting.csv")
agents = pd.read_csv(DATA_DIR / "agents.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

Store all DataFrames in one dictionary

In [7]:
datasets = {
    "customers": customers,
    "policies": policies,
    "claims": claims,
    "premiums": premiums,
    "renewals": renewals,
    "underwriting": underwriting,
    "agents": agents
}

In [8]:
for name, df in datasets.items():
    print(f"{name:15} -> {df.shape}")

customers       -> (100000, 12)
policies        -> (150000, 15)
claims          -> (75000, 14)
premiums        -> (100000, 10)
renewals        -> (20000, 12)
underwriting    -> (50000, 14)
agents          -> (5000, 10)

In [9]:
overview = []

for name, df in datasets.items():
    overview.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

overview_df = pd.DataFrame(overview)

overview_df

        Dataset    Rows  Columns  Missing Values  Duplicate Rows
0     customers  100000       12               0               0
1      policies  150000       15               0               0
2        claims   75000       14               0               0
3      premiums  100000       10           17678               0
4      renewals   20000       12               0               0
5  underwriting   50000       14            1537               0
6        agents    5000       10               0               0

In [10]:
customers.head()

,CUSTOMER_ID,CUSTOMER_NAME,AGE,GENDER,MARITAL_STATUS,OCCUPATION,ANNUAL_INCOME,STATE,CITY,CREDIT_SCORE,CUSTOMER_RISK_SEGMENT,CUSTOMER_SINCE
0,CUST00000001,INS-CUSTOMER-000001,62,Other,Married,Retired,380568,Uttar Pradesh,Kanpur,652,Medium,2018-04-24
1,CUST00000002,INS-CUSTOMER-000002,32,Female,Single,Salaried,120000,West Bengal,Kolkata,686,Low,2026-06-22
2,CUST00000003,INS-CUSTOMER-000003,45,Female,Married,Self Employed,706162,Odisha,Bhubaneswar,756,Low,2021-09-25
3,CUST00000004,INS-CUSTOMER-000004,25,Female,Married,Self Employed,557262,Rajasthan,Jodhpur,799,Low,2026-02-25
4,CUST00000005,INS-CUSTOMER-000005,38,Other,Married,Salaried,709830,Tamil Nadu,Salem,814,Medium,2021-08-16

In [11]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   CUSTOMER_ID            100000 non-null  str
 1   CUSTOMER_NAME          100000 non-null  str
 2   AGE                    100000 non-null  int64
 3   GENDER                 100000 non-null  str
 4   MARITAL_STATUS         100000 non-null  str
 5   OCCUPATION             100000 non-null  str
 6   ANNUAL_INCOME          100000 non-null  int64
 7   STATE                  100000 non-null  str
 8   CITY                   100000 non-null  str
 9   CREDIT_SCORE           100000 non-null  int64
 10  CUSTOMER_RISK_SEGMENT  100000 non-null  str
 11  CUSTOMER_SINCE         100000 non-null  str
dtypes: int64(3), str(9)
memory usage: 9.2 MB

In [12]:
customers.describe()

                 AGE  ANNUAL_INCOME   CREDIT_SCORE
count  100000.000000   1.000000e+05  100000.000000
mean       38.671880   8.311229e+05     719.502090
std        11.513542   6.567305e+05      69.892151
min        18.000000   1.200000e+05     450.000000
25%        30.000000   4.065565e+05     672.000000
50%        38.000000   6.493635e+05     720.000000
75%        47.000000   1.044275e+06     767.000000
max        80.000000   8.000000e+06     900.000000

Understand categorical columns

In [14]:
customers["GENDER"].value_counts()
customers["OCCUPATION"].value_counts()

OCCUPATION
Salaried               41732
Self Employed          18105
Business Owner         13062
Professional           10058
Government Employee    10030
Retired                 7013
Name: count, dtype: int64

In [15]:
customers["CUSTOMER_RISK_SEGMENT"].value_counts()

CUSTOMER_RISK_SEGMENT
Low       54974
Medium    34012
High      11014
Name: count, dtype: int64

Check missing values properly

In [16]:
customers.isnull().sum()

CUSTOMER_ID              0
CUSTOMER_NAME            0
AGE                      0
GENDER                   0
MARITAL_STATUS           0
OCCUPATION               0
ANNUAL_INCOME            0
STATE                    0
CITY                     0
CREDIT_SCORE             0
CUSTOMER_RISK_SEGMENT    0
CUSTOMER_SINCE           0
dtype: int64

In [17]:
for name, df in datasets.items():

    print("\n", "=" * 60)
    print(name.upper())
    print("=" * 60)

    missing = df.isnull().sum()

    print(missing[missing > 0])

 ============================================================
CUSTOMERS
============================================================
Series([], dtype: int64)

 ============================================================
POLICIES
============================================================
Series([], dtype: int64)

 ============================================================
CLAIMS
============================================================
Series([], dtype: int64)

 ============================================================
PREMIUMS
============================================================
PAID_DATE             8839
PAYMENT_DELAY_DAYS    8839
dtype: int64

 ============================================================
RENEWALS
============================================================
Series([], dtype: int64)

 ============================================================
UNDERWRITING
============================================================
PREMIUM_LOADING_PCT    1537
dtype: int64

 ============================================================
AGENTS
============================================================
Series([], dtype: int64)

In [18]:
for name, df in datasets.items():
    print(name, ":", df.duplicated().sum())

customers : 0
policies : 0
claims : 0
premiums : 0
renewals : 0
underwriting : 0
agents : 0

In [20]:
primary_keys = {
    "customers": "CUSTOMER_ID",
    "policies": "POLICY_ID",
    "claims": "CLAIM_ID",
    "premiums": "PREMIUM_TXN_ID",
    "renewals": "RENEWAL_ID",
    "underwriting": "UNDERWRITING_ID",
    "agents": "AGENT_ID"
}

for name, key in primary_keys.items():

    df = datasets[name]

    duplicate_ids = df[key].duplicated().sum()

    print(
        f"{name:15} | "
        f"Rows: {len(df):7} | "
        f"Unique {key}: {df[key].nunique():7} | "
        f"Duplicate IDs: {duplicate_ids}"
    )

customers       | Rows:  100000 | Unique CUSTOMER_ID:  100000 | Duplicate IDs: 0
policies        | Rows:  150000 | Unique POLICY_ID:  150000 | Duplicate IDs: 0
claims          | Rows:   75000 | Unique CLAIM_ID:   75000 | Duplicate IDs: 0
premiums        | Rows:  100000 | Unique PREMIUM_TXN_ID:  100000 | Duplicate IDs: 0
renewals        | Rows:   20000 | Unique RENEWAL_ID:   20000 | Duplicate IDs: 0
underwriting    | Rows:   50000 | Unique UNDERWRITING_ID:   50000 | Duplicate IDs: 0
agents          | Rows:    5000 | Unique AGENT_ID:    5000 | Duplicate IDs: 0

In [21]:
policies[["POLICY_ID", "CUSTOMER_ID"]].head()

      POLICY_ID   CUSTOMER_ID
0  POL000000001  CUST00047547
1  POL000000002  CUST00065458
2  POL000000003  CUST00074570
3  POL000000004  CUST00043802
4  POL000000005  CUST00015974

In [22]:
invalid_customers = policies[
    ~policies["CUSTOMER_ID"].isin(customers["CUSTOMER_ID"])
]

invalid_customers.shape

(0, 15)

Validate agent relationship

In [23]:
invalid_agents = policies[
    ~policies["AGENT_ID"].isin(agents["AGENT_ID"])
]

invalid_agents.shape

(0, 15)

Validate claims → policies

In [24]:
invalid_claim_policies = claims[
    ~claims["POLICY_ID"].isin(policies["POLICY_ID"])
]

invalid_claim_policies.shape

(0, 14)

Validate agent relationship

In [25]:
invalid_agents = policies[
    ~policies["AGENT_ID"].isin(agents["AGENT_ID"])
]

invalid_agents.shape

(0, 15)

Validate claims → policies

In [26]:
invalid_claim_policies = claims[
    ~claims["POLICY_ID"].isin(policies["POLICY_ID"])
]

invalid_claim_policies.shape

(0, 14)

In [ ]:
#Renewal Model
renewals["RENEWAL_STATUS"].value_counts()

RENEWAL_STATUS
Renewed      17334
Lapsed        1463
Pending        796
Cancelled      407
Name: count, dtype: int64

In [28]:
#Renewal Model
renewals["RENEWAL_STATUS"].value_counts()

RENEWAL_STATUS
Renewed      17334
Lapsed        1463
Pending        796
Cancelled      407
Name: count, dtype: int64

In [29]:
#Underwriting Model
underwriting["DECISION"].value_counts()

DECISION
Approved                 41717
Approved with Loading     6746
Declined                  1537
Name: count, dtype: int64

In [33]:
#Very important leakage discovery
renewals[
    [
        "RENEWAL_PROBABILITY",
        "RENEWAL_STATUS"
    ]
].head(10)

   RENEWAL_PROBABILITY RENEWAL_STATUS
0               0.8376        Renewed
1               0.9200        Renewed
2               0.8960        Renewed
3               0.9360        Renewed
4               0.8208        Renewed
5               0.8880      Cancelled
6               0.8698        Renewed
7               0.8320        Renewed
8               0.8188        Renewed
9               0.9120        Renewed

In [34]:
claims[
    [
        "FRAUD_SCORE",
        "FRAUD_FLAG"
    ]
].head(10)

   FRAUD_SCORE FRAUD_FLAG
0       0.1639         No
1       0.2701         No
2       0.2997         No
3       0.8973         No
4       0.2776         No
5       0.2712         No
6       0.7508         No
7       0.9719         No
8       0.3932         No
9       0.2025         No

In [35]:
underwriting[
    [
        "UNDERWRITING_SCORE",
        "DECISION"
    ]
].head(10)

   UNDERWRITING_SCORE               DECISION
0                 489  Approved with Loading
1                 653               Approved
2                 620               Approved
3                 630               Approved
4                 626               Approved
5                 649               Approved
6                 718               Approved
7                 522               Approved
8                 733               Approved
9                 550               Approved

In [37]:
overview = []

for name, df in datasets.items():
    total_cells = df.shape[0] * df.shape[1]
    missing = df.isnull().sum().sum()

    overview.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": missing,
        "Missing %": round((missing / total_cells) * 100, 2),
        "Duplicate Rows": df.duplicated().sum()
    })

overview_df = pd.DataFrame(overview)

overview_df

        Dataset    Rows  Columns  Missing Values  Missing %  Duplicate Rows
0     customers  100000       12               0       0.00               0
1      policies  150000       15               0       0.00               0
2        claims   75000       14               0       0.00               0
3      premiums  100000       10           17678       1.77               0
4      renewals   20000       12               0       0.00               0
5  underwriting   50000       14            1537       0.22               0
6        agents    5000       10               0       0.00               0

In [38]:
def inspect_dataset(df, name):
    print("=" * 70)
    print(f"DATASET: {name.upper()}")
    print("=" * 70)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nFirst 5 Rows:")
    display(df.head())

In [39]:
inspect_dataset(customers, "customers")

======================================================================
DATASET: CUSTOMERS
======================================================================

Shape:
(100000, 12)

Columns:
['CUSTOMER_ID', 'CUSTOMER_NAME', 'AGE', 'GENDER', 'MARITAL_STATUS', 'OCCUPATION', 'ANNUAL_INCOME', 'STATE', 'CITY', 'CREDIT_SCORE', 'CUSTOMER_RISK_SEGMENT', 'CUSTOMER_SINCE']

Data Types:
CUSTOMER_ID                str
CUSTOMER_NAME              str
AGE                      int64
GENDER                     str
MARITAL_STATUS             str
OCCUPATION                 str
ANNUAL_INCOME            int64
STATE                      str
CITY                       str
CREDIT_SCORE             int64
CUSTOMER_RISK_SEGMENT      str
CUSTOMER_SINCE             str
dtype: object

Missing Values:
CUSTOMER_ID              0
CUSTOMER_NAME            0
AGE                      0
GENDER                   0
MARITAL_STATUS           0
OCCUPATION               0
ANNUAL_INCOME            0
STATE                    0
CITY                     0
CREDIT_SCORE             0
CUSTOMER_RISK_SEGMENT    0
CUSTOMER_SINCE           0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,CUSTOMER_ID,CUSTOMER_NAME,AGE,GENDER,MARITAL_STATUS,OCCUPATION,ANNUAL_INCOME,STATE,CITY,CREDIT_SCORE,CUSTOMER_RISK_SEGMENT,CUSTOMER_SINCE
0,CUST00000001,INS-CUSTOMER-000001,62,Other,Married,Retired,380568,Uttar Pradesh,Kanpur,652,Medium,2018-04-24
1,CUST00000002,INS-CUSTOMER-000002,32,Female,Single,Salaried,120000,West Bengal,Kolkata,686,Low,2026-06-22
2,CUST00000003,INS-CUSTOMER-000003,45,Female,Married,Self Employed,706162,Odisha,Bhubaneswar,756,Low,2021-09-25
3,CUST00000004,INS-CUSTOMER-000004,25,Female,Married,Self Employed,557262,Rajasthan,Jodhpur,799,Low,2026-02-25
4,CUST00000005,INS-CUSTOMER-000005,38,Other,Married,Salaried,709830,Tamil Nadu,Salem,814,Medium,2021-08-16

In [40]:
for name, df in datasets.items():
    inspect_dataset(df, name)

======================================================================
DATASET: CUSTOMERS
======================================================================

Shape:
(100000, 12)

Columns:
['CUSTOMER_ID', 'CUSTOMER_NAME', 'AGE', 'GENDER', 'MARITAL_STATUS', 'OCCUPATION', 'ANNUAL_INCOME', 'STATE', 'CITY', 'CREDIT_SCORE', 'CUSTOMER_RISK_SEGMENT', 'CUSTOMER_SINCE']

Data Types:
CUSTOMER_ID                str
CUSTOMER_NAME              str
AGE                      int64
GENDER                     str
MARITAL_STATUS             str
OCCUPATION                 str
ANNUAL_INCOME            int64
STATE                      str
CITY                       str
CREDIT_SCORE             int64
CUSTOMER_RISK_SEGMENT      str
CUSTOMER_SINCE             str
dtype: object

Missing Values:
CUSTOMER_ID              0
CUSTOMER_NAME            0
AGE                      0
GENDER                   0
MARITAL_STATUS           0
OCCUPATION               0
ANNUAL_INCOME            0
STATE                    0
CITY                     0
CREDIT_SCORE             0
CUSTOMER_RISK_SEGMENT    0
CUSTOMER_SINCE           0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,CUSTOMER_ID,CUSTOMER_NAME,AGE,GENDER,MARITAL_STATUS,OCCUPATION,ANNUAL_INCOME,STATE,CITY,CREDIT_SCORE,CUSTOMER_RISK_SEGMENT,CUSTOMER_SINCE
0,CUST00000001,INS-CUSTOMER-000001,62,Other,Married,Retired,380568,Uttar Pradesh,Kanpur,652,Medium,2018-04-24
1,CUST00000002,INS-CUSTOMER-000002,32,Female,Single,Salaried,120000,West Bengal,Kolkata,686,Low,2026-06-22
2,CUST00000003,INS-CUSTOMER-000003,45,Female,Married,Self Employed,706162,Odisha,Bhubaneswar,756,Low,2021-09-25
3,CUST00000004,INS-CUSTOMER-000004,25,Female,Married,Self Employed,557262,Rajasthan,Jodhpur,799,Low,2026-02-25
4,CUST00000005,INS-CUSTOMER-000005,38,Other,Married,Salaried,709830,Tamil Nadu,Salem,814,Medium,2021-08-16

======================================================================
DATASET: POLICIES
======================================================================

Shape:
(150000, 15)

Columns:
['POLICY_ID', 'CUSTOMER_ID', 'POLICY_TYPE', 'SALES_CHANNEL', 'AGENT_ID', 'POLICY_START_DATE', 'POLICY_END_DATE', 'SUM_INSURED', 'ANNUAL_PREMIUM', 'PAYMENT_MODE', 'RISK_SCORE', 'RISK_BAND', 'POLICY_STATUS', 'DISCOUNT_PCT', 'COMMISSION_PCT']

Data Types:
POLICY_ID                str
CUSTOMER_ID              str
POLICY_TYPE              str
SALES_CHANNEL            str
AGENT_ID                 str
POLICY_START_DATE        str
POLICY_END_DATE          str
SUM_INSURED            int64
ANNUAL_PREMIUM         int64
PAYMENT_MODE             str
RISK_SCORE             int64
RISK_BAND                str
POLICY_STATUS            str
DISCOUNT_PCT         float64
COMMISSION_PCT       float64
dtype: object

Missing Values:
POLICY_ID            0
CUSTOMER_ID          0
POLICY_TYPE          0
SALES_CHANNEL        0
AGENT_ID             0
POLICY_START_DATE    0
POLICY_END_DATE      0
SUM_INSURED          0
ANNUAL_PREMIUM       0
PAYMENT_MODE         0
RISK_SCORE           0
RISK_BAND            0
POLICY_STATUS        0
DISCOUNT_PCT         0
COMMISSION_PCT       0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,POLICY_ID,CUSTOMER_ID,POLICY_TYPE,SALES_CHANNEL,AGENT_ID,POLICY_START_DATE,POLICY_END_DATE,SUM_INSURED,ANNUAL_PREMIUM,PAYMENT_MODE,RISK_SCORE,RISK_BAND,POLICY_STATUS,DISCOUNT_PCT,COMMISSION_PCT
0,POL000000001,CUST00047547,Motor,Corporate Partner,AGT004657,2022-06-14,2042-06-09,485748,11289,Annual,434,Low,Active,11.93,4.53
1,POL000000002,CUST00065458,Motor,Corporate Partner,AGT000403,2020-10-02,2021-10-02,496150,13822,Monthly,284,Low,Active,10.27,2.41
2,POL000000003,CUST00074570,Term Life,Agent,AGT003370,2023-12-30,2028-12-28,8290365,17205,Annual,391,Low,Active,10.42,3.57
3,POL000000004,CUST00043802,Motor,Bancassurance,AGT003064,2021-01-26,2022-01-26,321823,26296,Monthly,360,Low,Active,13.19,4.92
4,POL000000005,CUST00015974,Commercial,Broker,AGT003426,2023-05-21,2024-05-20,7695457,24541,Monthly,345,Low,Active,10.85,3.05

======================================================================
DATASET: CLAIMS
======================================================================

Shape:
(75000, 14)

Columns:
['CLAIM_ID', 'POLICY_ID', 'CUSTOMER_ID', 'CLAIM_TYPE', 'INCIDENT_DATE', 'REPORTED_DATE', 'CLAIM_AMOUNT', 'CLAIM_STATUS', 'SETTLEMENT_AMOUNT', 'PROCESSING_DAYS', 'FRAUD_FLAG', 'FRAUD_SCORE', 'SOURCE', 'CLAIM_SEVERITY']

Data Types:
CLAIM_ID                 str
POLICY_ID                str
CUSTOMER_ID              str
CLAIM_TYPE               str
INCIDENT_DATE            str
REPORTED_DATE            str
CLAIM_AMOUNT           int64
CLAIM_STATUS             str
SETTLEMENT_AMOUNT      int64
PROCESSING_DAYS        int64
FRAUD_FLAG               str
FRAUD_SCORE          float64
SOURCE                   str
CLAIM_SEVERITY           str
dtype: object

Missing Values:
CLAIM_ID             0
POLICY_ID            0
CUSTOMER_ID          0
CLAIM_TYPE           0
INCIDENT_DATE        0
REPORTED_DATE        0
CLAIM_AMOUNT         0
CLAIM_STATUS         0
SETTLEMENT_AMOUNT    0
PROCESSING_DAYS      0
FRAUD_FLAG           0
FRAUD_SCORE          0
SOURCE               0
CLAIM_SEVERITY       0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,CLAIM_ID,POLICY_ID,CUSTOMER_ID,CLAIM_TYPE,INCIDENT_DATE,REPORTED_DATE,CLAIM_AMOUNT,CLAIM_STATUS,SETTLEMENT_AMOUNT,PROCESSING_DAYS,FRAUD_FLAG,FRAUD_SCORE,SOURCE,CLAIM_SEVERITY
0,CLM000000001,POL000041446,CUST00025025,Vehicle Damage,2022-03-22,2022-03-24,1048663,Approved,1047821,30,No,0.1639,Surveyor,Medium
1,CLM000000002,POL000087254,CUST00082211,Theft,2026-06-26,2026-07-03,6584,Under Investigation,0,33,No,0.2701,Garage,Low
2,CLM000000003,POL000058180,CUST00020965,Death,2024-05-12,2024-05-18,109923,Approved,103624,18,No,0.2997,Surveyor,Low
3,CLM000000004,POL000105789,CUST00014259,Liability,2025-12-14,2025-12-20,276770,Approved,251398,12,No,0.8973,Hospital,Low
4,CLM000000005,POL000117667,CUST00067498,Travel Disruption,2022-11-18,2022-11-19,39463,Approved,39286,14,No,0.2776,Police,Medium

======================================================================
DATASET: PREMIUMS
======================================================================

Shape:
(100000, 10)

Columns:
['PREMIUM_TXN_ID', 'POLICY_ID', 'CUSTOMER_ID', 'DUE_DATE', 'PAID_DATE', 'PREMIUM_AMOUNT', 'PAYMENT_STATUS', 'PAYMENT_METHOD', 'PAYMENT_DELAY_DAYS', 'CHANNEL_COST']

Data Types:
PREMIUM_TXN_ID            str
POLICY_ID                 str
CUSTOMER_ID               str
DUE_DATE                  str
PAID_DATE                 str
PREMIUM_AMOUNT          int64
PAYMENT_STATUS            str
PAYMENT_METHOD            str
PAYMENT_DELAY_DAYS    float64
CHANNEL_COST          float64
dtype: object

Missing Values:
PREMIUM_TXN_ID           0
POLICY_ID                0
CUSTOMER_ID              0
DUE_DATE                 0
PAID_DATE             8839
PREMIUM_AMOUNT           0
PAYMENT_STATUS           0
PAYMENT_METHOD           0
PAYMENT_DELAY_DAYS    8839
CHANNEL_COST             0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

  PREMIUM_TXN_ID     POLICY_ID   CUSTOMER_ID    DUE_DATE   PAID_DATE  PREMIUM_AMOUNT PAYMENT_STATUS PAYMENT_METHOD  PAYMENT_DELAY_DAYS  CHANNEL_COST
0   PRM000000001  POL000067000  CUST00091358  2026-07-09  2026-07-11            3469           Paid    Net Banking                 2.0        122.68
1   PRM000000002  POL000077006  CUST00080746  2026-07-13         NaN           16283        Overdue     Auto Debit                 NaN        473.45
2   PRM000000003  POL000045385  CUST00051940  2025-05-01  2025-05-02            2224           Paid         Cheque                 1.0         67.58
3   PRM000000004  POL000060166  CUST00098054  2026-01-05  2026-01-05            3840           Paid            UPI                 0.0        105.30
4   PRM000000005  POL000072081  CUST00072564  2026-04-16  2026-04-29           22707           Paid            UPI                13.0        782.68

======================================================================
DATASET: RENEWALS
======================================================================

Shape:
(20000, 12)

Columns:
['RENEWAL_ID', 'POLICY_ID', 'CUSTOMER_ID', 'RENEWAL_DUE_DATE', 'OLD_PREMIUM', 'NEW_PREMIUM', 'PREMIUM_INCREASE_PCT', 'CLAIM_HISTORY_FLAG', 'LOYALTY_YEARS', 'RENEWAL_PROBABILITY', 'RENEWAL_STATUS', 'CONTACT_CHANNEL']

Data Types:
RENEWAL_ID                  str
POLICY_ID                   str
CUSTOMER_ID                 str
RENEWAL_DUE_DATE            str
OLD_PREMIUM               int64
NEW_PREMIUM               int64
PREMIUM_INCREASE_PCT    float64
CLAIM_HISTORY_FLAG          str
LOYALTY_YEARS             int64
RENEWAL_PROBABILITY     float64
RENEWAL_STATUS              str
CONTACT_CHANNEL             str
dtype: object

Missing Values:
RENEWAL_ID              0
POLICY_ID               0
CUSTOMER_ID             0
RENEWAL_DUE_DATE        0
OLD_PREMIUM             0
NEW_PREMIUM             0
PREMIUM_INCREASE_PCT    0
CLAIM_HISTORY_FLAG      0
LOYALTY_YEARS           0
RENEWAL_PROBABILITY     0
RENEWAL_STATUS          0
CONTACT_CHANNEL         0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,RENEWAL_ID,POLICY_ID,CUSTOMER_ID,RENEWAL_DUE_DATE,OLD_PREMIUM,NEW_PREMIUM,PREMIUM_INCREASE_PCT,CLAIM_HISTORY_FLAG,LOYALTY_YEARS,RENEWAL_PROBABILITY,RENEWAL_STATUS,CONTACT_CHANNEL
0,REN00000001,POL000051250,CUST00059258,2025-06-17,11390,12441,9.23,Yes,7,0.8376,Renewed,WhatsApp
1,REN00000002,POL000017253,CUST00094235,2026-08-14,13513,13983,3.48,No,5,0.9200,Renewed,SMS
2,REN00000003,POL000108220,CUST00031120,2025-04-17,20696,20942,1.19,No,2,0.8960,Renewed,SMS
3,REN00000004,POL000068626,CUST00061811,2025-08-30,11112,11584,4.25,No,7,0.9360,Renewed,Call
4,REN00000005,POL000134055,CUST00024866,2026-02-13,13833,15043,8.75,Yes,4,0.8208,Renewed,SMS

======================================================================
DATASET: UNDERWRITING
======================================================================

Shape:
(50000, 14)

Columns:
['UNDERWRITING_ID', 'POLICY_ID', 'CUSTOMER_ID', 'AGE', 'HEALTH_SCORE', 'LIFESTYLE', 'MEDICAL_HISTORY_FLAG', 'SMOKER_FLAG', 'BMI', 'OCCUPATION_RISK', 'CREDIT_SCORE', 'UNDERWRITING_SCORE', 'DECISION', 'PREMIUM_LOADING_PCT']

Data Types:
UNDERWRITING_ID             str
POLICY_ID                   str
CUSTOMER_ID                 str
AGE                       int64
HEALTH_SCORE              int64
LIFESTYLE                   str
MEDICAL_HISTORY_FLAG        str
SMOKER_FLAG                 str
BMI                     float64
OCCUPATION_RISK             str
CREDIT_SCORE              int64
UNDERWRITING_SCORE        int64
DECISION                    str
PREMIUM_LOADING_PCT     float64
dtype: object

Missing Values:
UNDERWRITING_ID            0
POLICY_ID                  0
CUSTOMER_ID                0
AGE                        0
HEALTH_SCORE               0
LIFESTYLE                  0
MEDICAL_HISTORY_FLAG       0
SMOKER_FLAG                0
BMI                        0
OCCUPATION_RISK            0
CREDIT_SCORE               0
UNDERWRITING_SCORE         0
DECISION                   0
PREMIUM_LOADING_PCT     1537
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,UNDERWRITING_ID,POLICY_ID,CUSTOMER_ID,AGE,HEALTH_SCORE,LIFESTYLE,MEDICAL_HISTORY_FLAG,SMOKER_FLAG,BMI,OCCUPATION_RISK,CREDIT_SCORE,UNDERWRITING_SCORE,DECISION,PREMIUM_LOADING_PCT
0,UW00000001,POL000075805,CUST00024107,37,63,Good,No,No,26.0,Medium,789,489,Approved with Loading,18.44
1,UW00000002,POL000061636,CUST00009702,37,86,Excellent,No,Yes,27.5,Medium,616,653,Approved,0.00
2,UW00000003,POL000109448,CUST00044764,38,86,Average,No,No,31.6,Low,701,620,Approved,0.00
3,UW00000004,POL000003539,CUST00099336,20,81,Good,No,No,29.3,Low,739,630,Approved,0.00
4,UW00000005,POL000023463,CUST00035999,49,76,Good,No,No,22.6,Low,630,626,Approved,0.00

======================================================================
DATASET: AGENTS
======================================================================

Shape:
(5000, 10)

Columns:
['AGENT_ID', 'AGENT_NAME', 'AGENT_TYPE', 'REGION', 'EXPERIENCE_YEARS', 'COMMISSION_PCT', 'POLICIES_SOLD', 'RENEWAL_RATE_PCT', 'STATUS', 'JOIN_DATE']

Data Types:
AGENT_ID                str
AGENT_NAME              str
AGENT_TYPE              str
REGION                  str
EXPERIENCE_YEARS      int64
COMMISSION_PCT      float64
POLICIES_SOLD         int64
RENEWAL_RATE_PCT    float64
STATUS                  str
JOIN_DATE               str
dtype: object

Missing Values:
AGENT_ID            0
AGENT_NAME          0
AGENT_TYPE          0
REGION              0
EXPERIENCE_YEARS    0
COMMISSION_PCT      0
POLICIES_SOLD       0
RENEWAL_RATE_PCT    0
STATUS              0
JOIN_DATE           0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

    AGENT_ID   AGENT_NAME        AGENT_TYPE   REGION  EXPERIENCE_YEARS  COMMISSION_PCT  POLICIES_SOLD  RENEWAL_RATE_PCT    STATUS   JOIN_DATE
0  AGT000001  Agent 00001            Broker     West                 3            6.97            398             88.87    Active  2024-10-05
1  AGT000002  Agent 00002      Bank Partner    South                 3            1.98             48             90.26    Active  2024-04-27
2  AGT000003  Agent 00003   Digital Partner     West                 2           10.21            199             71.33  Inactive  2020-12-02
3  AGT000004  Agent 00004  Individual Agent    North                 1           10.13            251             84.79    Active  2026-02-06
4  AGT000005  Agent 00005   Corporate Agent  Central                 1            7.11            394             78.15    Active  2019-08-04

In [41]:
inspect_dataset(customers, "customers")

======================================================================
DATASET: CUSTOMERS
======================================================================

Shape:
(100000, 12)

Columns:
['CUSTOMER_ID', 'CUSTOMER_NAME', 'AGE', 'GENDER', 'MARITAL_STATUS', 'OCCUPATION', 'ANNUAL_INCOME', 'STATE', 'CITY', 'CREDIT_SCORE', 'CUSTOMER_RISK_SEGMENT', 'CUSTOMER_SINCE']

Data Types:
CUSTOMER_ID                str
CUSTOMER_NAME              str
AGE                      int64
GENDER                     str
MARITAL_STATUS             str
OCCUPATION                 str
ANNUAL_INCOME            int64
STATE                      str
CITY                       str
CREDIT_SCORE             int64
CUSTOMER_RISK_SEGMENT      str
CUSTOMER_SINCE             str
dtype: object

Missing Values:
CUSTOMER_ID              0
CUSTOMER_NAME            0
AGE                      0
GENDER                   0
MARITAL_STATUS           0
OCCUPATION               0
ANNUAL_INCOME            0
STATE                    0
CITY                     0
CREDIT_SCORE             0
CUSTOMER_RISK_SEGMENT    0
CUSTOMER_SINCE           0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,CUSTOMER_ID,CUSTOMER_NAME,AGE,GENDER,MARITAL_STATUS,OCCUPATION,ANNUAL_INCOME,STATE,CITY,CREDIT_SCORE,CUSTOMER_RISK_SEGMENT,CUSTOMER_SINCE
0,CUST00000001,INS-CUSTOMER-000001,62,Other,Married,Retired,380568,Uttar Pradesh,Kanpur,652,Medium,2018-04-24
1,CUST00000002,INS-CUSTOMER-000002,32,Female,Single,Salaried,120000,West Bengal,Kolkata,686,Low,2026-06-22
2,CUST00000003,INS-CUSTOMER-000003,45,Female,Married,Self Employed,706162,Odisha,Bhubaneswar,756,Low,2021-09-25
3,CUST00000004,INS-CUSTOMER-000004,25,Female,Married,Self Employed,557262,Rajasthan,Jodhpur,799,Low,2026-02-25
4,CUST00000005,INS-CUSTOMER-000005,38,Other,Married,Salaried,709830,Tamil Nadu,Salem,814,Medium,2021-08-16

In [42]:
customers["CUSTOMER_SINCE"].dtype

In [43]:
customers["CUSTOMER_SINCE"] = pd.to_datetime(
    customers["CUSTOMER_SINCE"]
)

In [44]:
customers.describe()

                 AGE  ANNUAL_INCOME   CREDIT_SCORE              CUSTOMER_SINCE
count  100000.000000   1.000000e+05  100000.000000                      100000
mean       38.671880   8.311229e+05     719.502090  2022-05-05 02:59:53.088000
min        18.000000   1.200000e+05     450.000000         2018-01-01 00:00:00
25%        30.000000   4.065565e+05     672.000000         2020-03-05 00:00:00
50%        38.000000   6.493635e+05     720.000000         2022-05-04 00:00:00
75%        47.000000   1.044275e+06     767.000000         2024-07-08 00:00:00
max        80.000000   8.000000e+06     900.000000         2026-08-31 00:00:00
std        11.513542   6.567305e+05      69.892151                         NaN

In [46]:
print("Total rows:", len(customers))
print("Unique Customer IDs:", customers["CUSTOMER_ID"].nunique())
print(
    "Duplicate Customer IDs:",
    customers["CUSTOMER_ID"].duplicated().sum()
)

Total rows: 100000
Unique Customer IDs: 100000
Duplicate Customer IDs: 0

In [47]:
customers["CUSTOMER_ID"].isnull().sum()

np.int64(0)

In [48]:
inspect_dataset(customers, "customers")
customers.info()
customers.describe()
customers.nunique()

======================================================================
DATASET: CUSTOMERS
======================================================================

Shape:
(100000, 12)

Columns:
['CUSTOMER_ID', 'CUSTOMER_NAME', 'AGE', 'GENDER', 'MARITAL_STATUS', 'OCCUPATION', 'ANNUAL_INCOME', 'STATE', 'CITY', 'CREDIT_SCORE', 'CUSTOMER_RISK_SEGMENT', 'CUSTOMER_SINCE']

Data Types:
CUSTOMER_ID                         str
CUSTOMER_NAME                       str
AGE                               int64
GENDER                              str
MARITAL_STATUS                      str
OCCUPATION                          str
ANNUAL_INCOME                     int64
STATE                               str
CITY                                str
CREDIT_SCORE                      int64
CUSTOMER_RISK_SEGMENT               str
CUSTOMER_SINCE           datetime64[us]
dtype: object

Missing Values:
CUSTOMER_ID              0
CUSTOMER_NAME            0
AGE                      0
GENDER                   0
MARITAL_STATUS           0
OCCUPATION               0
ANNUAL_INCOME            0
STATE                    0
CITY                     0
CREDIT_SCORE             0
CUSTOMER_RISK_SEGMENT    0
CUSTOMER_SINCE           0
dtype: int64

Duplicate Rows:
0

First 5 Rows:

,CUSTOMER_ID,CUSTOMER_NAME,AGE,GENDER,MARITAL_STATUS,OCCUPATION,ANNUAL_INCOME,STATE,CITY,CREDIT_SCORE,CUSTOMER_RISK_SEGMENT,CUSTOMER_SINCE
0,CUST00000001,INS-CUSTOMER-000001,62,Other,Married,Retired,380568,Uttar Pradesh,Kanpur,652,Medium,2018-04-24
1,CUST00000002,INS-CUSTOMER-000002,32,Female,Single,Salaried,120000,West Bengal,Kolkata,686,Low,2026-06-22
2,CUST00000003,INS-CUSTOMER-000003,45,Female,Married,Self Employed,706162,Odisha,Bhubaneswar,756,Low,2021-09-25
3,CUST00000004,INS-CUSTOMER-000004,25,Female,Married,Self Employed,557262,Rajasthan,Jodhpur,799,Low,2026-02-25
4,CUST00000005,INS-CUSTOMER-000005,38,Other,Married,Salaried,709830,Tamil Nadu,Salem,814,Medium,2021-08-16

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   CUSTOMER_ID            100000 non-null  str
 1   CUSTOMER_NAME          100000 non-null  str
 2   AGE                    100000 non-null  int64
 3   GENDER                 100000 non-null  str
 4   MARITAL_STATUS         100000 non-null  str
 5   OCCUPATION             100000 non-null  str
 6   ANNUAL_INCOME          100000 non-null  int64
 7   STATE                  100000 non-null  str
 8   CITY                   100000 non-null  str
 9   CREDIT_SCORE           100000 non-null  int64
 10  CUSTOMER_RISK_SEGMENT  100000 non-null  str
 11  CUSTOMER_SINCE         100000 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(3), str(8)
memory usage: 9.2 MB

CUSTOMER_ID              100000
CUSTOMER_NAME            100000
AGE                          63
GENDER                        3
MARITAL_STATUS                4
OCCUPATION                    6
ANNUAL_INCOME             95833
STATE                        11
CITY                         44
CREDIT_SCORE                432
CUSTOMER_RISK_SEGMENT         3
CUSTOMER_SINCE             3165
dtype: int64

In [49]:
print("Total Rows:", len(customers))
print("Unique Customer IDs:", customers["CUSTOMER_ID"].nunique())
print("Duplicate IDs:", customers["CUSTOMER_ID"].duplicated().sum())
print("Missing IDs:", customers["CUSTOMER_ID"].isnull().sum())

Total Rows: 100000
Unique Customer IDs: 100000
Duplicate IDs: 0
Missing IDs: 0

In [50]:
print("AGE RANGE")
print(customers["AGE"].min(), "-", customers["AGE"].max())

print("\nINCOME RANGE")
print(customers["ANNUAL_INCOME"].min(), "-", customers["ANNUAL_INCOME"].max())

print("\nCREDIT SCORE RANGE")
print(customers["CREDIT_SCORE"].min(), "-", customers["CREDIT_SCORE"].max())

AGE RANGE
18 - 80

INCOME RANGE
120000 - 8000000

CREDIT SCORE RANGE
450 - 900

In [51]:
categorical_columns = [
    "GENDER",
    "MARITAL_STATUS",
    "OCCUPATION",
    "STATE",
    "CUSTOMER_RISK_SEGMENT"
]

for col in categorical_columns:
    print("\n", "=" * 50)
    print(col)
    print("=" * 50)
    print(customers[col].value_counts(dropna=False))

 ==================================================
GENDER
==================================================
GENDER
Female    33499
Male      33281
Other     33220
Name: count, dtype: int64

 ==================================================
MARITAL_STATUS
==================================================
MARITAL_STATUS
Married     58173
Single      34020
Divorced     3934
Widowed      3873
Name: count, dtype: int64

 ==================================================
OCCUPATION
==================================================
OCCUPATION
Salaried               41732
Self Employed          18105
Business Owner         13062
Professional           10058
Government Employee    10030
Retired                 7013
Name: count, dtype: int64

 ==================================================
STATE
==================================================
STATE
Telangana        9261
Gujarat          9218
West Bengal      9196
Rajasthan        9145
Odisha           9141
Kerala           9086
Tamil Nadu       9075
Karnataka        9052
Maharashtra      8961
Delhi            8938
Uttar Pradesh    8927
Name: count, dtype: int64

 ==================================================
CUSTOMER_RISK_SEGMENT
==================================================
CUSTOMER_RISK_SEGMENT
Low       54974
Medium    34012
High      11014
Name: count, dtype: int64

In [52]:
print(customers["CUSTOMER_SINCE"].dtype)

print(
    customers["CUSTOMER_SINCE"].head()
)

datetime64[us]
0   2018-04-24
1   2026-06-22
2   2021-09-25
3   2026-02-25
4   2021-08-16
Name: CUSTOMER_SINCE, dtype: datetime64[us]

In [54]:
customer_summary = {
    "Total Customers": len(customers),
    "Unique Customers": customers["CUSTOMER_ID"].nunique(),
    "Duplicate IDs": customers["CUSTOMER_ID"].duplicated().sum(),
    "Missing IDs": customers["CUSTOMER_ID"].isnull().sum(),
    "Min Age": customers["AGE"].min(),
    "Max Age": customers["AGE"].max(),
    "Min Income": customers["ANNUAL_INCOME"].min(),
    "Max Income": customers["ANNUAL_INCOME"].max(),
    "Min Credit Score": customers["CREDIT_SCORE"].min(),
    "Max Credit Score": customers["CREDIT_SCORE"].max(),
    "Earliest Customer": customers["CUSTOMER_SINCE"].min(),
    "Latest Customer": customers["CUSTOMER_SINCE"].max()
}

pd.Series(customer_summary)

Total Customers                   100000
Unique Customers                  100000
Duplicate IDs                          0
Missing IDs                            0
Min Age                               18
Max Age                               80
Min Income                        120000
Max Income                       8000000
Min Credit Score                     450
Max Credit Score                     900
Earliest Customer    2018-01-01 00:00:00
Latest Customer      2026-08-31 00:00:00
dtype: object

In [55]:
#policy.csv
policies.head()

,POLICY_ID,CUSTOMER_ID,POLICY_TYPE,SALES_CHANNEL,AGENT_ID,POLICY_START_DATE,POLICY_END_DATE,SUM_INSURED,ANNUAL_PREMIUM,PAYMENT_MODE,RISK_SCORE,RISK_BAND,POLICY_STATUS,DISCOUNT_PCT,COMMISSION_PCT
0,POL000000001,CUST00047547,Motor,Corporate Partner,AGT004657,2022-06-14,2042-06-09,485748,11289,Annual,434,Low,Active,11.93,4.53
1,POL000000002,CUST00065458,Motor,Corporate Partner,AGT000403,2020-10-02,2021-10-02,496150,13822,Monthly,284,Low,Active,10.27,2.41
2,POL000000003,CUST00074570,Term Life,Agent,AGT003370,2023-12-30,2028-12-28,8290365,17205,Annual,391,Low,Active,10.42,3.57
3,POL000000004,CUST00043802,Motor,Bancassurance,AGT003064,2021-01-26,2022-01-26,321823,26296,Monthly,360,Low,Active,13.19,4.92
4,POL000000005,CUST00015974,Commercial,Broker,AGT003426,2023-05-21,2024-05-20,7695457,24541,Monthly,345,Low,Active,10.85,3.05

In [56]:
policies.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   POLICY_ID          150000 non-null  str
 1   CUSTOMER_ID        150000 non-null  str
 2   POLICY_TYPE        150000 non-null  str
 3   SALES_CHANNEL      150000 non-null  str
 4   AGENT_ID           150000 non-null  str
 5   POLICY_START_DATE  150000 non-null  str
 6   POLICY_END_DATE    150000 non-null  str
 7   SUM_INSURED        150000 non-null  int64
 8   ANNUAL_PREMIUM     150000 non-null  int64
 9   PAYMENT_MODE       150000 non-null  str
 10  RISK_SCORE         150000 non-null  int64
 11  RISK_BAND          150000 non-null  str
 12  POLICY_STATUS      150000 non-null  str
 13  DISCOUNT_PCT       150000 non-null  float64
 14  COMMISSION_PCT     150000 non-null  float64
dtypes: float64(2), int64(3), str(10)
memory usage: 17.2 MB

In [57]:
policies.columns.tolist()

['POLICY_ID',
 'CUSTOMER_ID',
 'POLICY_TYPE',
 'SALES_CHANNEL',
 'AGENT_ID',
 'POLICY_START_DATE',
 'POLICY_END_DATE',
 'SUM_INSURED',
 'ANNUAL_PREMIUM',
 'PAYMENT_MODE',
 'RISK_SCORE',
 'RISK_BAND',
 'POLICY_STATUS',
 'DISCOUNT_PCT',
 'COMMISSION_PCT']

In [58]:
print("Total Policies      :", len(policies))
print("Unique Policy IDs   :", policies["POLICY_ID"].nunique())
print("Duplicate Policy IDs:", policies["POLICY_ID"].duplicated().sum())
print("Missing Policy IDs  :", policies["POLICY_ID"].isnull().sum())

Total Policies      : 150000
Unique Policy IDs   : 150000
Duplicate Policy IDs: 0
Missing Policy IDs  : 0

In [59]:
print("Unique Customers in Policies:",
      policies["CUSTOMER_ID"].nunique())

print("Total Customers:",
      customers["CUSTOMER_ID"].nunique())

Unique Customers in Policies: 77891
Total Customers: 100000

In [60]:
invalid_policy_customers = policies[
    ~policies["CUSTOMER_ID"].isin(customers["CUSTOMER_ID"])
]

print("Policies with invalid Customer ID:",
      len(invalid_policy_customers))

Policies with invalid Customer ID: 0

In [62]:
invalid_agents = policies[
    ~policies["AGENT_ID"].isin(agents["AGENT_ID"])
]

print("Invalid Agent References:", len(invalid_agents))

Invalid Agent References: 0

In [63]:
policy_cat_cols = [
    "POLICY_TYPE",
    "SALES_CHANNEL",
    "PAYMENT_MODE",
    "RISK_BAND",
    "POLICY_STATUS"
]

for col in policy_cat_cols:
    print("\n" + "=" * 50)
    print(col)
    print("=" * 50)

    print(policies[col].value_counts())

==================================================
POLICY_TYPE
==================================================
POLICY_TYPE
Health               36123
Motor                31768
Term Life            23933
Commercial           14892
Home                 12031
Personal Accident    11989
Whole Life           10302
Travel                8962
Name: count, dtype: int64

==================================================
SALES_CHANNEL
==================================================
SALES_CHANNEL
Bancassurance        25305
Corporate Partner    25171
Agent                25043
Direct               24957
Broker               24791
Online               24733
Name: count, dtype: int64

==================================================
PAYMENT_MODE
==================================================
PAYMENT_MODE
Annual         75273
Monthly        44770
Quarterly      17964
Half-Yearly    11993
Name: count, dtype: int64

==================================================
RISK_BAND
==================================================
RISK_BAND
Low       123356
Medium     26382
High         262
Name: count, dtype: int64

==================================================
POLICY_STATUS
==================================================
POLICY_STATUS
Active       104959
Expired       21019
Lapsed        14914
Cancelled      9108
Name: count, dtype: int64

In [64]:

policies[
    [
        "SUM_INSURED",
        "ANNUAL_PREMIUM",
        "RISK_SCORE",
        "DISCOUNT_PCT",
        "COMMISSION_PCT"
    ]
].describe()

        SUM_INSURED  ANNUAL_PREMIUM     RISK_SCORE   DISCOUNT_PCT  COMMISSION_PCT
count  1.500000e+05   150000.000000  150000.000000  150000.000000   150000.000000
mean   2.558792e+06    19195.141140     415.727507      10.007650        2.509821
std    2.960261e+06    14113.463906      68.643447       5.781533        1.440787
min    1.000000e+05     1200.000000     250.000000       0.000000        0.000000
25%    5.866960e+05    10513.000000     369.000000       5.010000        1.270000
50%    1.169048e+06    15628.000000     415.000000      10.010000        2.510000
75%    3.732162e+06    23199.000000     462.000000      15.020000        3.750000
max    2.500000e+07   186032.000000     744.000000      20.000000        5.000000

In [65]:
policy_summary = {
    "Total Policies": len(policies),
    "Unique Policies": policies["POLICY_ID"].nunique(),
    "Unique Customers": policies["CUSTOMER_ID"].nunique(),
    "Unique Agents": policies["AGENT_ID"].nunique(),
    "Duplicate Policy IDs": policies["POLICY_ID"].duplicated().sum(),
    "Missing Policy IDs": policies["POLICY_ID"].isnull().sum(),
    "Earliest Start Date": policies["POLICY_START_DATE"].min(),
    "Latest Start Date": policies["POLICY_START_DATE"].max(),
    "Invalid Date Records": (
        policies["POLICY_END_DATE"] <
        policies["POLICY_START_DATE"]
    ).sum()
}

pd.Series(policy_summary)

Total Policies              150000
Unique Policies             150000
Unique Customers             77891
Unique Agents                 5000
Duplicate Policy IDs             0
Missing Policy IDs               0
Earliest Start Date     2019-01-01
Latest Start Date       2026-08-31
Invalid Date Records             0
dtype: object

claims

In [66]:
claims.info()
claims.nunique()

<class 'pandas.DataFrame'>
RangeIndex: 75000 entries, 0 to 74999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CLAIM_ID           75000 non-null  str
 1   POLICY_ID          75000 non-null  str
 2   CUSTOMER_ID        75000 non-null  str
 3   CLAIM_TYPE         75000 non-null  str
 4   INCIDENT_DATE      75000 non-null  str
 5   REPORTED_DATE      75000 non-null  str
 6   CLAIM_AMOUNT       75000 non-null  int64
 7   CLAIM_STATUS       75000 non-null  str
 8   SETTLEMENT_AMOUNT  75000 non-null  int64
 9   PROCESSING_DAYS    75000 non-null  int64
 10  FRAUD_FLAG         75000 non-null  str
 11  FRAUD_SCORE        75000 non-null  float64
 12  SOURCE             75000 non-null  str
 13  CLAIM_SEVERITY     75000 non-null  str
dtypes: float64(1), int64(3), str(10)
memory usage: 8.0 MB

CLAIM_ID             75000
POLICY_ID            58905
CUSTOMER_ID          44619
CLAIM_TYPE               8
INCIDENT_DATE         1704
REPORTED_DATE         1720
CLAIM_AMOUNT         67288
CLAIM_STATUS             5
SETTLEMENT_AMOUNT    50929
PROCESSING_DAYS         99
FRAUD_FLAG               3
FRAUD_SCORE           9996
SOURCE                   6
CLAIM_SEVERITY           3
dtype: int64

In [67]:
claims["FRAUD_FLAG"].value_counts()

FRAUD_FLAG
No           72841
Suspected     1815
Confirmed      344
Name: count, dtype: int64

In [68]:
claims.select_dtypes(include=np.number).describe()

       CLAIM_AMOUNT  SETTLEMENT_AMOUNT  PROCESSING_DAYS   FRAUD_SCORE
count  7.500000e+04       7.500000e+04     75000.000000  75000.000000
mean   3.063485e+05       1.967341e+05        20.512053      0.498369
std    6.084179e+05       4.773754e+05        12.152669      0.288381
min    2.000000e+03       0.000000e+00         1.000000      0.000000
25%    4.103175e+04       0.000000e+00        12.000000      0.247900
50%    1.090645e+05       4.814900e+04        18.000000      0.498500
75%    3.112128e+05       1.822520e+05        27.000000      0.748200
max    1.599195e+07       1.444330e+07       120.000000      1.000000

In [69]:
print("Duplicate Claim IDs:", claims["CLAIM_ID"].duplicated().sum())

print(
    "Invalid Policy IDs:",
    (~claims["POLICY_ID"].isin(policies["POLICY_ID"])).sum()
)

Duplicate Claim IDs: 0
Invalid Policy IDs: 0

Premium

In [70]:
premiums.info()
premiums.nunique()
premiums.head()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   PREMIUM_TXN_ID      100000 non-null  str
 1   POLICY_ID           100000 non-null  str
 2   CUSTOMER_ID         100000 non-null  str
 3   DUE_DATE            100000 non-null  str
 4   PAID_DATE           91161 non-null   str
 5   PREMIUM_AMOUNT      100000 non-null  int64
 6   PAYMENT_STATUS      100000 non-null  str
 7   PAYMENT_METHOD      100000 non-null  str
 8   PAYMENT_DELAY_DAYS  91161 non-null   float64
 9   CHANNEL_COST        100000 non-null  float64
dtypes: float64(2), int64(1), str(7)
memory usage: 7.6 MB

  PREMIUM_TXN_ID     POLICY_ID   CUSTOMER_ID    DUE_DATE   PAID_DATE  PREMIUM_AMOUNT PAYMENT_STATUS PAYMENT_METHOD  PAYMENT_DELAY_DAYS  CHANNEL_COST
0   PRM000000001  POL000067000  CUST00091358  2026-07-09  2026-07-11            3469           Paid    Net Banking                 2.0        122.68
1   PRM000000002  POL000077006  CUST00080746  2026-07-13         NaN           16283        Overdue     Auto Debit                 NaN        473.45
2   PRM000000003  POL000045385  CUST00051940  2025-05-01  2025-05-02            2224           Paid         Cheque                 1.0         67.58
3   PRM000000004  POL000060166  CUST00098054  2026-01-05  2026-01-05            3840           Paid            UPI                 0.0        105.30
4   PRM000000005  POL000072081  CUST00072564  2026-04-16  2026-04-29           22707           Paid            UPI                13.0        782.68

In [71]:
print("Duplicate Premium IDs:",
      premiums["PREMIUM_TXN_ID"].duplicated().sum())

Duplicate Premium IDs: 0

In [72]:
print(
    "Invalid Policy IDs:",
    (~premiums["POLICY_ID"].isin(policies["POLICY_ID"])).sum()
)

Invalid Policy IDs: 0

In [73]:
premiums["PAYMENT_STATUS"].value_counts()

PAYMENT_STATUS
Paid       91161
Overdue     3979
Pending     2846
Failed      2014
Name: count, dtype: int64

In [74]:
premiums.select_dtypes(include=np.number).describe()

       PREMIUM_AMOUNT  PAYMENT_DELAY_DAYS  CHANNEL_COST
count   100000.000000        91161.000000  100000.00000
mean     10669.340050            6.744704     320.47276
std      12771.211033            8.159359     428.88020
min        100.000000            0.000000       1.25000
25%       1661.000000            0.000000      47.96000
50%       5886.500000            4.000000     159.07500
75%      15234.000000           12.000000     434.92000
max     148331.000000           60.000000    5646.06000

Rewneals

In [75]:
renewals.info()
renewals.nunique()
renewals.head()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   RENEWAL_ID            20000 non-null  str
 1   POLICY_ID             20000 non-null  str
 2   CUSTOMER_ID           20000 non-null  str
 3   RENEWAL_DUE_DATE      20000 non-null  str
 4   OLD_PREMIUM           20000 non-null  int64
 5   NEW_PREMIUM           20000 non-null  int64
 6   PREMIUM_INCREASE_PCT  20000 non-null  float64
 7   CLAIM_HISTORY_FLAG    20000 non-null  str
 8   LOYALTY_YEARS         20000 non-null  int64
 9   RENEWAL_PROBABILITY   20000 non-null  float64
 10  RENEWAL_STATUS        20000 non-null  str
 11  CONTACT_CHANNEL       20000 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 1.8 MB

,RENEWAL_ID,POLICY_ID,CUSTOMER_ID,RENEWAL_DUE_DATE,OLD_PREMIUM,NEW_PREMIUM,PREMIUM_INCREASE_PCT,CLAIM_HISTORY_FLAG,LOYALTY_YEARS,RENEWAL_PROBABILITY,RENEWAL_STATUS,CONTACT_CHANNEL
0,REN00000001,POL000051250,CUST00059258,2025-06-17,11390,12441,9.23,Yes,7,0.8376,Renewed,WhatsApp
1,REN00000002,POL000017253,CUST00094235,2026-08-14,13513,13983,3.48,No,5,0.9200,Renewed,SMS
2,REN00000003,POL000108220,CUST00031120,2025-04-17,20696,20942,1.19,No,2,0.8960,Renewed,SMS
3,REN00000004,POL000068626,CUST00061811,2025-08-30,11112,11584,4.25,No,7,0.9360,Renewed,Call
4,REN00000005,POL000134055,CUST00024866,2026-02-13,13833,15043,8.75,Yes,4,0.8208,Renewed,SMS

In [76]:
renewals["RENEWAL_STATUS"].value_counts()

RENEWAL_STATUS
Renewed      17334
Lapsed        1463
Pending        796
Cancelled      407
Name: count, dtype: int64

In [77]:
renewals["RENEWAL_STATUS"].value_counts(normalize=True) * 100

RENEWAL_STATUS
Renewed      86.670
Lapsed        7.315
Pending       3.980
Cancelled     2.035
Name: proportion, dtype: float64

In [78]:
print(
    "Duplicate Renewal IDs:",
    renewals["RENEWAL_ID"].duplicated().sum()
)

Duplicate Renewal IDs: 0

In [79]:
print(
    "Invalid Policy IDs:",
    (~renewals["POLICY_ID"].isin(policies["POLICY_ID"])).sum()
)

Invalid Policy IDs: 0

In [80]:
renewals[
    ["RENEWAL_PROBABILITY", "RENEWAL_STATUS"]
].head(20)

    RENEWAL_PROBABILITY RENEWAL_STATUS
0                0.8376        Renewed
1                0.9200        Renewed
2                0.8960        Renewed
3                0.9360        Renewed
4                0.8208        Renewed
5                0.8880      Cancelled
6                0.8698        Renewed
7                0.8320        Renewed
8                0.8188        Renewed
9                0.9120        Renewed
10               0.9040        Renewed
11               0.8320        Renewed
12               0.9200        Pending
13               0.8960         Lapsed
14               0.8160        Renewed
15               0.9104        Renewed
16               0.9057        Renewed
17               0.9200        Renewed
18               0.8030        Renewed
19               0.8880        Renewed

In [81]:
renewals["PREMIUM_INCREASE_PCT"] = (
    (renewals["NEW_PREMIUM"] - renewals["OLD_PREMIUM"])
    / renewals["OLD_PREMIUM"]
) * 100

In [82]:
renewals["PREMIUM_INCREASE_PCT"].describe()

count    20000.000000
mean         7.037202
std          4.954253
min        -11.201902
25%          3.678688
50%          7.066720
75%         10.407734
max         33.358237
Name: PREMIUM_INCREASE_PCT, dtype: float64

Underwiting

In [83]:
underwriting.info()
underwriting.nunique()
underwriting.head()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   UNDERWRITING_ID       50000 non-null  str
 1   POLICY_ID             50000 non-null  str
 2   CUSTOMER_ID           50000 non-null  str
 3   AGE                   50000 non-null  int64
 4   HEALTH_SCORE          50000 non-null  int64
 5   LIFESTYLE             50000 non-null  str
 6   MEDICAL_HISTORY_FLAG  50000 non-null  str
 7   SMOKER_FLAG           50000 non-null  str
 8   BMI                   50000 non-null  float64
 9   OCCUPATION_RISK       50000 non-null  str
 10  CREDIT_SCORE          50000 non-null  int64
 11  UNDERWRITING_SCORE    50000 non-null  int64
 12  DECISION              50000 non-null  str
 13  PREMIUM_LOADING_PCT   48463 non-null  float64
dtypes: float64(2), int64(4), str(8)
memory usage: 5.3 MB

,UNDERWRITING_ID,POLICY_ID,CUSTOMER_ID,AGE,HEALTH_SCORE,LIFESTYLE,MEDICAL_HISTORY_FLAG,SMOKER_FLAG,BMI,OCCUPATION_RISK,CREDIT_SCORE,UNDERWRITING_SCORE,DECISION,PREMIUM_LOADING_PCT
0,UW00000001,POL000075805,CUST00024107,37,63,Good,No,No,26.0,Medium,789,489,Approved with Loading,18.44
1,UW00000002,POL000061636,CUST00009702,37,86,Excellent,No,Yes,27.5,Medium,616,653,Approved,0.00
2,UW00000003,POL000109448,CUST00044764,38,86,Average,No,No,31.6,Low,701,620,Approved,0.00
3,UW00000004,POL000003539,CUST00099336,20,81,Good,No,No,29.3,Low,739,630,Approved,0.00
4,UW00000005,POL000023463,CUST00035999,49,76,Good,No,No,22.6,Low,630,626,Approved,0.00

In [84]:
underwriting["DECISION"].value_counts()

DECISION
Approved                 41717
Approved with Loading     6746
Declined                  1537
Name: count, dtype: int64

In [85]:
underwriting["DECISION"].value_counts(normalize=True) * 100

DECISION
Approved                 83.434
Approved with Loading    13.492
Declined                  3.074
Name: proportion, dtype: float64

In [86]:
print(
    "Duplicate Underwriting IDs:",
    underwriting["UNDERWRITING_ID"].duplicated().sum()
)

Duplicate Underwriting IDs: 0

In [87]:
print(
    "Invalid Customer IDs:",
    (~underwriting["CUSTOMER_ID"].isin(customers["CUSTOMER_ID"])).sum()
)

Invalid Customer IDs: 0

In [88]:
underwriting[
    ["UNDERWRITING_SCORE", "DECISION"]
].head(20)

    UNDERWRITING_SCORE               DECISION
0                  489  Approved with Loading
1                  653               Approved
2                  620               Approved
3                  630               Approved
4                  626               Approved
5                  649               Approved
6                  718               Approved
7                  522               Approved
8                  733               Approved
9                  550               Approved
10                 661               Approved
11                 624               Approved
12                 495  Approved with Loading
13                 515  Approved with Loading
14                 813               Approved
15                 387               Declined
16                 756               Approved
17                 682               Approved
18                 526               Approved
19                 597               Approved

Agent.csv

In [89]:
agents.info()
agents.nunique()
agents.head()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AGENT_ID          5000 non-null   str
 1   AGENT_NAME        5000 non-null   str
 2   AGENT_TYPE        5000 non-null   str
 3   REGION            5000 non-null   str
 4   EXPERIENCE_YEARS  5000 non-null   int64
 5   COMMISSION_PCT    5000 non-null   float64
 6   POLICIES_SOLD     5000 non-null   int64
 7   RENEWAL_RATE_PCT  5000 non-null   float64
 8   STATUS            5000 non-null   str
 9   JOIN_DATE         5000 non-null   str
dtypes: float64(2), int64(2), str(6)
memory usage: 390.8 KB

    AGENT_ID   AGENT_NAME        AGENT_TYPE   REGION  EXPERIENCE_YEARS  COMMISSION_PCT  POLICIES_SOLD  RENEWAL_RATE_PCT    STATUS   JOIN_DATE
0  AGT000001  Agent 00001            Broker     West                 3            6.97            398             88.87    Active  2024-10-05
1  AGT000002  Agent 00002      Bank Partner    South                 3            1.98             48             90.26    Active  2024-04-27
2  AGT000003  Agent 00003   Digital Partner     West                 2           10.21            199             71.33  Inactive  2020-12-02
3  AGT000004  Agent 00004  Individual Agent    North                 1           10.13            251             84.79    Active  2026-02-06
4  AGT000005  Agent 00005   Corporate Agent  Central                 1            7.11            394             78.15    Active  2019-08-04

In [90]:
agents.select_dtypes(include="object").columns.tolist()

C:\Users\asus\AppData\Local\Temp\ipykernel_26284\854459344.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  agents.select_dtypes(include="object").columns.tolist()

['AGENT_ID', 'AGENT_NAME', 'AGENT_TYPE', 'REGION', 'STATUS', 'JOIN_DATE']

In [91]:
for col in agents.select_dtypes(include="object").columns:
    print("\n", col)
    print(agents[col].value_counts().head(10))

 AGENT_ID
AGENT_ID
AGT000001    1
AGT000002    1
AGT000003    1
AGT000004    1
AGT000005    1
AGT000006    1
AGT000007    1
AGT000008    1
AGT000009    1
AGT000010    1
Name: count, dtype: int64

 AGENT_NAME
AGENT_NAME
Agent 00001    1
Agent 00002    1
Agent 00003    1
Agent 00004    1
Agent 00005    1
Agent 00006    1
Agent 00007    1
Agent 00008    1
Agent 00009    1
Agent 00010    1
Name: count, dtype: int64

 AGENT_TYPE
AGENT_TYPE
Individual Agent    1024
Digital Partner     1011
Bank Partner        1000
Broker               998
Corporate Agent      967
Name: count, dtype: int64

 REGION
REGION
West       1029
East       1021
Central    1008
North       996
South       946
Name: count, dtype: int64

 STATUS
STATUS
Active      4545
Inactive     455
Name: count, dtype: int64

 JOIN_DATE
JOIN_DATE
2016-07-10    7
2018-03-24    6
2018-08-29    6
2018-02-24    6
2022-12-27    6
2020-10-09    6
2021-09-03    6
2023-10-15    5
2023-08-31    5
2016-06-19    5
Name: count, dtype: int64

C:\Users\asus\AppData\Local\Temp\ipykernel_26284\4112001606.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in agents.select_dtypes(include="object").columns:

In [92]:
# Foreign key validation

checks = {
    "Policy -> Customer": (~policies["CUSTOMER_ID"].isin(customers["CUSTOMER_ID"])).sum(),
    "Policy -> Agent": (~policies["AGENT_ID"].isin(agents["AGENT_ID"])).sum(),
    "Claim -> Policy": (~claims["POLICY_ID"].isin(policies["POLICY_ID"])).sum(),
    "Premium -> Policy": (~premiums["POLICY_ID"].isin(policies["POLICY_ID"])).sum(),
    "Renewal -> Policy": (~renewals["POLICY_ID"].isin(policies["POLICY_ID"])).sum(),
    "Underwriting -> Customer": (~underwriting["CUSTOMER_ID"].isin(customers["CUSTOMER_ID"])).sum()
}

pd.Series(checks)

Policy -> Customer          0
Policy -> Agent             0
Claim -> Policy             0
Premium -> Policy           0
Renewal -> Policy           0
Underwriting -> Customer    0
dtype: int64

In [93]:
primary_keys = {
    "customers": "CUSTOMER_ID",
    "policies": "POLICY_ID",
    "claims": "CLAIM_ID",
    "premiums": "PREMIUM_TXN_ID",
    "renewals": "RENEWAL_ID",
    "underwriting": "UNDERWRITING_ID",
    "agents": "AGENT_ID"
}

for name, key in primary_keys.items():
    df = datasets[name]

    print(
        name,
        "| duplicates:", df[key].duplicated().sum(),
        "| missing:", df[key].isnull().sum()
    )

customers | duplicates: 0 | missing: 0
policies | duplicates: 0 | missing: 0
claims | duplicates: 0 | missing: 0
premiums | duplicates: 0 | missing: 0
renewals | duplicates: 0 | missing: 0
underwriting | duplicates: 0 | missing: 0
agents | duplicates: 0 | missing: 0