In [1]:
# Basic libraries
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
# Define project and data paths
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "raw"

# Load underwriting data
underwriting = pd.read_csv(
    DATA_DIR / "underwriting.csv"
)

print("Dataset Shape:", underwriting.shape)

underwriting.head()

Dataset Shape: (50000, 14)

,UNDERWRITING_ID,POLICY_ID,CUSTOMER_ID,AGE,HEALTH_SCORE,LIFESTYLE,MEDICAL_HISTORY_FLAG,SMOKER_FLAG,BMI,OCCUPATION_RISK,CREDIT_SCORE,UNDERWRITING_SCORE,DECISION,PREMIUM_LOADING_PCT
0,UW00000001,POL000075805,CUST00024107,37,63,Good,No,No,26.0,Medium,789,489,Approved with Loading,18.44
1,UW00000002,POL000061636,CUST00009702,37,86,Excellent,No,Yes,27.5,Medium,616,653,Approved,0.00
2,UW00000003,POL000109448,CUST00044764,38,86,Average,No,No,31.6,Low,701,620,Approved,0.00
3,UW00000004,POL000003539,CUST00099336,20,81,Good,No,No,29.3,Low,739,630,Approved,0.00
4,UW00000005,POL000023463,CUST00035999,49,76,Good,No,No,22.6,Low,630,626,Approved,0.00

In [3]:
# Define project and data paths
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data" / "raw"

# Load underwriting data
underwriting = pd.read_csv(
    DATA_DIR / "underwriting.csv"
)

print("Dataset Shape:", underwriting.shape)

underwriting.head()

Dataset Shape: (50000, 14)

,UNDERWRITING_ID,POLICY_ID,CUSTOMER_ID,AGE,HEALTH_SCORE,LIFESTYLE,MEDICAL_HISTORY_FLAG,SMOKER_FLAG,BMI,OCCUPATION_RISK,CREDIT_SCORE,UNDERWRITING_SCORE,DECISION,PREMIUM_LOADING_PCT
0,UW00000001,POL000075805,CUST00024107,37,63,Good,No,No,26.0,Medium,789,489,Approved with Loading,18.44
1,UW00000002,POL000061636,CUST00009702,37,86,Excellent,No,Yes,27.5,Medium,616,653,Approved,0.00
2,UW00000003,POL000109448,CUST00044764,38,86,Average,No,No,31.6,Low,701,620,Approved,0.00
3,UW00000004,POL000003539,CUST00099336,20,81,Good,No,No,29.3,Low,739,630,Approved,0.00
4,UW00000005,POL000023463,CUST00035999,49,76,Good,No,No,22.6,Low,630,626,Approved,0.00

In [4]:
# Check columns and data types
underwriting.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   UNDERWRITING_ID       50000 non-null  str
 1   POLICY_ID             50000 non-null  str
 2   CUSTOMER_ID           50000 non-null  str
 3   AGE                   50000 non-null  int64
 4   HEALTH_SCORE          50000 non-null  int64
 5   LIFESTYLE             50000 non-null  str
 6   MEDICAL_HISTORY_FLAG  50000 non-null  str
 7   SMOKER_FLAG           50000 non-null  str
 8   BMI                   50000 non-null  float64
 9   OCCUPATION_RISK       50000 non-null  str
 10  CREDIT_SCORE          50000 non-null  int64
 11  UNDERWRITING_SCORE    50000 non-null  int64
 12  DECISION              50000 non-null  str
 13  PREMIUM_LOADING_PCT   48463 non-null  float64
dtypes: float64(2), int64(4), str(8)
memory usage: 5.3 MB

In [5]:
# Check columns and data types
underwriting.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   UNDERWRITING_ID       50000 non-null  str
 1   POLICY_ID             50000 non-null  str
 2   CUSTOMER_ID           50000 non-null  str
 3   AGE                   50000 non-null  int64
 4   HEALTH_SCORE          50000 non-null  int64
 5   LIFESTYLE             50000 non-null  str
 6   MEDICAL_HISTORY_FLAG  50000 non-null  str
 7   SMOKER_FLAG           50000 non-null  str
 8   BMI                   50000 non-null  float64
 9   OCCUPATION_RISK       50000 non-null  str
 10  CREDIT_SCORE          50000 non-null  int64
 11  UNDERWRITING_SCORE    50000 non-null  int64
 12  DECISION              50000 non-null  str
 13  PREMIUM_LOADING_PCT   48463 non-null  float64
dtypes: float64(2), int64(4), str(8)
memory usage: 5.3 MB

In [6]:
# Underwriting decision is our target
underwriting["DECISION"].value_counts()

DECISION
Approved                 41717
Approved with Loading     6746
Declined                  1537
Name: count, dtype: int64

In [7]:
# Check class distribution in percentage
underwriting["DECISION"].value_counts(
    normalize=True
) * 100

DECISION
Approved                 83.434
Approved with Loading    13.492
Declined                  3.074
Name: proportion, dtype: float64

In [8]:
# Check missing values
underwriting.isnull().sum()

UNDERWRITING_ID            0
POLICY_ID                  0
CUSTOMER_ID                0
AGE                        0
HEALTH_SCORE               0
LIFESTYLE                  0
MEDICAL_HISTORY_FLAG       0
SMOKER_FLAG                0
BMI                        0
OCCUPATION_RISK            0
CREDIT_SCORE               0
UNDERWRITING_SCORE         0
DECISION                   0
PREMIUM_LOADING_PCT     1537
dtype: int64

In [9]:
# Numerical model features
numeric_features = [
    "AGE",
    "HEALTH_SCORE",
    "BMI",
    "CREDIT_SCORE"
]

# Categorical model features
categorical_features = [
    "LIFESTYLE",
    "MEDICAL_HISTORY_FLAG",
    "SMOKER_FLAG",
    "OCCUPATION_RISK"
]

# Combine both
all_features = numeric_features + categorical_features

In [10]:
# Check whether every selected feature exists
missing_features = [
    col for col in all_features
    if col not in underwriting.columns
]

print("Missing features:", missing_features)

Missing features: []

In [11]:
# X = input features
X = underwriting[all_features].copy()

# y = target
y = underwriting["DECISION"].copy()

print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (50000, 8)
y Shape: (50000,)

In [12]:
# Import train-test split function
from sklearn.model_selection import train_test_split

# Split data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Train Shape:", X_train.shape)
print("Test Shape :", X_test.shape)

Train Shape: (40000, 8)
Test Shape : (10000, 8)

In [14]:
# Tools for preprocessing numeric and categorical columns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

In [15]:
# Numeric preprocessing:
# 1. Fill missing values with median
# 2. Standardize numeric values

numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

In [16]:
# Categorical preprocessing:
# 1. Fill missing values with most frequent category
# 2. Convert categories into 0/1 columns

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [17]:
# Apply different preprocessing to different feature types
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [18]:
# Import Logistic Regression classifier
from sklearn.linear_model import LogisticRegression

# Create complete preprocessing + model pipeline
uw_lr = Pipeline(
    steps=[
        ("preprocessor", preprocessor),

        ("model", LogisticRegression(
            class_weight="balanced",
            max_iter=1500,
            random_state=42
        ))
    ]
)

In [19]:
# Train underwriting Logistic Regression model
uw_lr.fit(
    X_train,
    y_train
)

print("Logistic Regression trained successfully")

Logistic Regression trained successfully

In [20]:
# Predict final underwriting class
lr_pred = uw_lr.predict(X_test)

# Predict probability for every class
lr_prob = uw_lr.predict_proba(X_test)

In [22]:
# Import evaluation metrics
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Calculate overall metrics
lr_accuracy = accuracy_score(
    y_test,
    lr_pred
)

lr_macro_f1 = f1_score(
    y_test,
    lr_pred,
    average="macro"
)

lr_weighted_f1 = f1_score(
    y_test,
    lr_pred,
    average="weighted"
)

print("Accuracy    :", round(lr_accuracy, 4))
print("Macro F1    :", round(lr_macro_f1, 4))
print("Weighted F1 :", round(lr_weighted_f1, 4))

Accuracy    : 0.8462
Macro F1    : 0.6982
Weighted F1 : 0.8632

In [23]:
# Check precision, recall and F1 for each underwriting class
print(
    classification_report(
        y_test,
        lr_pred
    )
)

                       precision    recall  f1-score   support

             Approved       0.98      0.87      0.92      8344
Approved with Loading       0.46      0.72      0.56      1349
             Declined       0.49      0.82      0.61       307

             accuracy                           0.85     10000
            macro avg       0.64      0.80      0.70     10000
         weighted avg       0.90      0.85      0.86     10000

In [24]:
# Check which classes model is confusing
lr_cm = confusion_matrix(
    y_test,
    lr_pred
)

print(lr_cm)

[[7244 1089   11]
 [ 132  965  252]
 [   0   54  253]]

In [25]:
# Import Random Forest classifier
from sklearn.ensemble import RandomForestClassifier

# Build preprocessing + Random Forest pipeline
uw_rf = Pipeline(
    steps=[
        ("preprocessor", preprocessor),

        ("model", RandomForestClassifier(
            n_estimators=300,        # Total trees
            max_depth=12,            # Maximum depth of each tree
            min_samples_split=10,    # Minimum rows needed to split
            min_samples_leaf=5,      # Minimum rows in a leaf
            class_weight="balanced", # Handle class imbalance
            random_state=42,
            n_jobs=-1
        ))
    ]
)

In [26]:
# Train Random Forest
uw_rf.fit(
    X_train,
    y_train
)

print("Random Forest trained successfully")

Random Forest trained successfully

In [27]:
# Predict underwriting classes
rf_pred = uw_rf.predict(X_test)

# Predict class probabilities
rf_prob = uw_rf.predict_proba(X_test)

In [28]:
# Calculate Random Forest metrics
rf_accuracy = accuracy_score(y_test, rf_pred)

rf_macro_f1 = f1_score(
    y_test,
    rf_pred,
    average="macro"
)

rf_weighted_f1 = f1_score(
    y_test,
    rf_pred,
    average="weighted"
)

print("Accuracy    :", round(rf_accuracy, 4))
print("Macro F1    :", round(rf_macro_f1, 4))
print("Weighted F1 :", round(rf_weighted_f1, 4))

Accuracy    : 0.8361
Macro F1    : 0.6948
Weighted F1 : 0.8553

In [29]:
# Class-wise performance
print(
    classification_report(
        y_test,
        rf_pred
    )
)

                       precision    recall  f1-score   support

             Approved       0.98      0.85      0.91      8344
Approved with Loading       0.44      0.76      0.56      1349
             Declined       0.52      0.75      0.62       307

             accuracy                           0.84     10000
            macro avg       0.65      0.78      0.69     10000
         weighted avg       0.89      0.84      0.86     10000

In [30]:
# Compare Logistic Regression and Random Forest
uw_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest"
    ],
    "Accuracy": [
        lr_accuracy,
        rf_accuracy
    ],
    "Macro F1": [
        lr_macro_f1,
        rf_macro_f1
    ],
    "Weighted F1": [
        lr_weighted_f1,
        rf_weighted_f1
    ]
})

uw_comparison

                 Model  Accuracy  Macro F1  Weighted F1
0  Logistic Regression    0.8462  0.698247     0.863195
1        Random Forest    0.8361  0.694781     0.855284

In [31]:
# Convert text target classes into numeric labels
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# See class-to-number mapping
class_mapping = dict(
    zip(
        label_encoder.classes_,
        label_encoder.transform(label_encoder.classes_)
    )
)

print(class_mapping)

{'Approved': np.int64(0), 'Approved with Loading': np.int64(1), 'Declined': np.int64(2)}

In [32]:
# Give more training importance to minority classes
from sklearn.utils.class_weight import compute_sample_weight

sample_weights = compute_sample_weight(
    class_weight="balanced",
    y=y_train_encoded
)

print("Training rows:", len(y_train_encoded))
print("Sample weights:", len(sample_weights))

Training rows: 40000
Sample weights: 40000

In [33]:
# Import XGBoost classifier
from xgboost import XGBClassifier

# Preprocessing + multiclass XGBoost pipeline
uw_xgb = Pipeline(
    steps=[
        ("preprocessor", preprocessor),

        ("model", XGBClassifier(
            objective="multi:softprob",   # Predict probability for each class
            num_class=len(label_encoder.classes_),

            n_estimators=300,             # Number of boosting trees
            max_depth=5,                  # Tree complexity
            learning_rate=0.05,           # Learning speed

            subsample=0.8,                # Use 80% rows per tree
            colsample_bytree=0.8,         # Use 80% features per tree

            eval_metric="mlogloss",
            random_state=42,
            n_jobs=-1
        ))
    ]
)

In [34]:
# Train XGBoost with balanced sample weights
uw_xgb.fit(
    X_train,
    y_train_encoded,
    model__sample_weight=sample_weights
)

print("Underwriting XGBoost trained successfully")

Underwriting XGBoost trained successfully

In [35]:
# Train XGBoost with balanced sample weights
uw_xgb.fit(
    X_train,
    y_train_encoded,
    model__sample_weight=sample_weights
)

print("Underwriting XGBoost trained successfully")

Underwriting XGBoost trained successfully

In [37]:
# Predict numeric class labels
xgb_pred_encoded = uw_xgb.predict(X_test)

# Convert numeric predictions back to original class names
xgb_pred = label_encoder.inverse_transform(
    xgb_pred_encoded.astype(int)
)

# Probability for each underwriting class
xgb_prob = uw_xgb.predict_proba(X_test)

In [38]:
# Calculate multiclass metrics
xgb_accuracy = accuracy_score(
    y_test,
    xgb_pred
)

xgb_macro_f1 = f1_score(
    y_test,
    xgb_pred,
    average="macro"
)

xgb_weighted_f1 = f1_score(
    y_test,
    xgb_pred,
    average="weighted"
)

print("Accuracy    :", round(xgb_accuracy, 4))
print("Macro F1    :", round(xgb_macro_f1, 4))
print("Weighted F1 :", round(xgb_weighted_f1, 4))

Accuracy    : 0.8421
Macro F1    : 0.6971
Weighted F1 : 0.8601

In [39]:
# Precision, Recall and F1 for every decision class
print(
    classification_report(
        y_test,
        xgb_pred
    )
)

                       precision    recall  f1-score   support

             Approved       0.98      0.86      0.92      8344
Approved with Loading       0.45      0.75      0.56      1349
             Declined       0.51      0.77      0.61       307

             accuracy                           0.84     10000
            macro avg       0.65      0.79      0.70     10000
         weighted avg       0.90      0.84      0.86     10000

In [40]:
# Compare all underwriting models
uw_comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],

    "Accuracy": [
        lr_accuracy,
        rf_accuracy,
        xgb_accuracy
    ],

    "Macro F1": [
        lr_macro_f1,
        rf_macro_f1,
        xgb_macro_f1
    ],

    "Weighted F1": [
        lr_weighted_f1,
        rf_weighted_f1,
        xgb_weighted_f1
    ]
})

uw_comparison

                 Model  Accuracy  Macro F1  Weighted F1
0  Logistic Regression    0.8462  0.698247     0.863195
1        Random Forest    0.8361  0.694781     0.855284
2              XGBoost    0.8421  0.697112     0.860065

In [41]:
# Get feature names after preprocessing
feature_names = (
    uw_xgb
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

# Get feature importance values from XGBoost
importance = (
    uw_xgb
    .named_steps["model"]
    .feature_importances_
)

# Build feature importance table
uw_feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

# Most important features first
uw_feature_importance = uw_feature_importance.sort_values(
    "Importance",
    ascending=False
)

uw_feature_importance.head(15)

                          Feature  Importance
1               num__HEALTH_SCORE    0.475714
3               num__CREDIT_SCORE    0.084595
2                        num__BMI    0.070160
0                        num__AGE    0.042332
11           cat__SMOKER_FLAG_Yes    0.039134
10            cat__SMOKER_FLAG_No    0.031092
8    cat__MEDICAL_HISTORY_FLAG_No    0.030990
13       cat__OCCUPATION_RISK_Low    0.030208
9   cat__MEDICAL_HISTORY_FLAG_Yes    0.029984
12      cat__OCCUPATION_RISK_High    0.029732
5        cat__LIFESTYLE_Excellent    0.028033
6             cat__LIFESTYLE_Good    0.027315
4          cat__LIFESTYLE_Average    0.027141
14    cat__OCCUPATION_RISK_Medium    0.026933
7             cat__LIFESTYLE_Poor    0.026636

In [45]:
# Import model saving library
import joblib

# Define models folder
MODEL_DIR = PROJECT_ROOT / "models"

# Create folder if needed
MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Save trained underwriting XGBoost pipeline
joblib.dump(
    uw_xgb,
    MODEL_DIR / "underwriting_xgboost_model.joblib"
)

# Save label encoder
joblib.dump(
    label_encoder,
    MODEL_DIR / "underwriting_label_encoder.joblib"
)

print("Underwriting model saved successfully")

Underwriting model saved successfully

In [46]:
# Import libraries
from pathlib import Path
import joblib

# Define models folder
PROJECT_ROOT = Path.cwd().parent
MODEL_DIR = PROJECT_ROOT / "models"

# Show all saved model files
for file in MODEL_DIR.glob("*.joblib"):
    print(file.name)

fraud_threshold.joblib
fraud_xgboost_model.joblib
renewal_churn_threshold.joblib
renewal_xgboost_model.joblib
underwriting_label_encoder.joblib
underwriting_xgboost_model.joblib

In [49]:
# Load Renewal model and threshold
renewal_model = joblib.load(
    MODEL_DIR / "renewal_xgboost_model.joblib"
)

renewal_threshold = joblib.load(
    MODEL_DIR / "renewal_churn_threshold.joblib"
)

# Load Fraud model and threshold
fraud_model = joblib.load(
    MODEL_DIR / "fraud_xgboost_model.joblib"
)

fraud_threshold = joblib.load(
    MODEL_DIR / "fraud_threshold.joblib"
)

# Load Underwriting model and label encoder
underwriting_model = joblib.load(
    MODEL_DIR / "underwriting_xgboost_model.joblib"
)

underwriting_encoder = joblib.load(
    MODEL_DIR / "underwriting_label_encoder.joblib"
)

print("All models loaded successfully")

All models loaded successfully

In [50]:
# Basic smoke test
print("Renewal Model      :", type(renewal_model))
print("Renewal Threshold  :", renewal_threshold)

print("\nFraud Model        :", type(fraud_model))
print("Fraud Threshold    :", fraud_threshold)

print("\nUnderwriting Model :", type(underwriting_model))
print(
    "Underwriting Classes:",
    underwriting_encoder.classes_
)

Renewal Model      : <class 'sklearn.pipeline.Pipeline'>
Renewal Threshold  : 0.4

Fraud Model        : <class 'sklearn.pipeline.Pipeline'>
Fraud Threshold    : 0.5

Underwriting Model : <class 'sklearn.pipeline.Pipeline'>
Underwriting Classes: ['Approved' 'Approved with Loading' 'Declined']

In [51]:
# Columns expected by our Underwriting API
api_test_cols = [
    "AGE",
    "HEALTH_SCORE",
    "BMI",
    "CREDIT_SCORE",
    "LIFESTYLE",
    "MEDICAL_HISTORY_FLAG",
    "SMOKER_FLAG",
    "OCCUPATION_RISK"
]

# Print one real record as JSON
print(
    underwriting[
        api_test_cols
    ].iloc[0].to_json(indent=2)
)

{
  "AGE":37,
  "HEALTH_SCORE":63,
  "BMI":26.0,
  "CREDIT_SCORE":789,
  "LIFESTYLE":"Good",
  "MEDICAL_HISTORY_FLAG":"No",
  "SMOKER_FLAG":"No",
  "OCCUPATION_RISK":"Medium"
}